version: "3.6"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db  
  db:
    image: mongo:latest
    environment:
      MONGO_URI: "mongodb://localhost:27017/"
    ports:
      - "27017:27017"
    volumes: #cat /etc/mongod.conf | grep dbPath
      - ./data:/var/lib/mongodb